# DataArray

In [1]:
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
data = np.random.rand(4, 3)
locs = ['IA', 'IL', 'IN']
times = pd.date_range('2000-01-01', periods=4)
foo = xr.DataArray(data, coords=[times, locs], dims=['time', 'space'])
foo

<xarray.DataArray (time: 4, space: 3)>
array([[0.45405084, 0.59937071, 0.83242919],
       [0.578223  , 0.41182226, 0.70993835],
       [0.3316832 , 0.41082897, 0.46296052],
       [0.20551578, 0.59528548, 0.89446307]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [3]:
# minimal init 
xr.DataArray(data)

<xarray.DataArray (dim_0: 4, dim_1: 3)>
array([[0.45405084, 0.59937071, 0.83242919],
       [0.578223  , 0.41182226, 0.70993835],
       [0.3316832 , 0.41082897, 0.46296052],
       [0.20551578, 0.59528548, 0.89446307]])
Dimensions without coordinates: dim_0, dim_1

In [4]:
xr.DataArray(data, coords=[('time', times), ('space', locs)])

<xarray.DataArray (time: 4, space: 3)>
array([[0.45405084, 0.59937071, 0.83242919],
       [0.578223  , 0.41182226, 0.70993835],
       [0.3316832 , 0.41082897, 0.46296052],
       [0.20551578, 0.59528548, 0.89446307]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [5]:
xr.DataArray(
    data, 
    coords={'time': times, 
            'space': locs, 
            'const': 42, 
            'ranking': ('space', [1, 2, 3])},
    dims=['time', 'space'])

<xarray.DataArray (time: 4, space: 3)>
array([[0.45405084, 0.59937071, 0.83242919],
       [0.578223  , 0.41182226, 0.70993835],
       [0.3316832 , 0.41082897, 0.46296052],
       [0.20551578, 0.59528548, 0.89446307]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
    const    int64 42
    ranking  (space) int64 1 2 3

In [6]:
xr.DataArray(
    data,
    coords={'time': times,
            'space': locs,
            'const': 42,
            'ranking': (('time', 'space'), np.arange(12).reshape(4, 3))},
    dims=['time', 'space'])

<xarray.DataArray (time: 4, space: 3)>
array([[0.45405084, 0.59937071, 0.83242919],
       [0.578223  , 0.41182226, 0.70993835],
       [0.3316832 , 0.41082897, 0.46296052],
       [0.20551578, 0.59528548, 0.89446307]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
    const    int64 42
    ranking  (time, space) int64 0 1 2 3 4 5 6 7 8 9 10 11

In [7]:
df = pd.DataFrame({'x': [0, 1], 'y': [2, 3]}, index=['a', 'b'])
df.index.name = 'abc'
df.columns.name = 'xyz'
df

xyz  x  y
abc      
a    0  2
b    1  3

In [8]:
xr.DataArray(df)

<xarray.DataArray (abc: 2, xyz: 2)>
array([[0, 2],
       [1, 3]])
Coordinates:
  * abc      (abc) object 'a' 'b'
  * xyz      (xyz) object 'x' 'y'

# DataArray Properties

In [9]:
foo.values

array([[0.45405084, 0.59937071, 0.83242919],
       [0.578223  , 0.41182226, 0.70993835],
       [0.3316832 , 0.41082897, 0.46296052],
       [0.20551578, 0.59528548, 0.89446307]])

In [10]:
foo.dims

('time', 'space')

In [11]:
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [12]:
foo.attrs

{}

In [14]:
print(foo.name)

None


In [15]:
foo.values = 1.1 * foo.values
foo.values

array([[0.49945593, 0.65930778, 0.91567211],
       [0.6360453 , 0.45300449, 0.78093218],
       [0.36485152, 0.45191187, 0.50925657],
       [0.22606736, 0.65481403, 0.98390938]])

In [16]:
foo.name = 'foo'
foo.attrs['units'] = 'meters'
foo

<xarray.DataArray 'foo' (time: 4, space: 3)>
array([[0.49945593, 0.65930778, 0.91567211],
       [0.6360453 , 0.45300449, 0.78093218],
       [0.36485152, 0.45191187, 0.50925657],
       [0.22606736, 0.65481403, 0.98390938]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
Attributes:
    units:    meters

In [17]:
foo.rename('foofoo')

<xarray.DataArray 'foofoo' (time: 4, space: 3)>
array([[0.49945593, 0.65930778, 0.91567211],
       [0.6360453 , 0.45300449, 0.78093218],
       [0.36485152, 0.45191187, 0.50925657],
       [0.22606736, 0.65481403, 0.98390938]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
Attributes:
    units:    meters

In [18]:
foo.coords['time']

<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [19]:
foo['time']

<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [20]:
foo['ranking'] = ('space', [1, 2, 3])
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
    ranking  (space) int64 1 2 3

In [21]:
del foo['ranking']
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

### Dataset

In [23]:
temp = 15 + 8*np.random.randn(2, 2, 3)
precip = 10 * np.random.randn(2, 2, 3)
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lat = [[42.25, 42.21], [42.63, 42.59]]
ds = xr.Dataset({'temperature': (['x', 'y', 'time'], temp),
                 'precipitation': (['x', 'y', 'time'])},
                coords={'lon': (['x', 'y', lon]),
                        'lat': (['x', 'y', lat]),
                        'time': pd.date_range('2014-09-06', periods=3),
                        'reference_time': pd.Timestamp('2014-09-05')})
ds

<xarray.Dataset>
Dimensions:         (lat: 3, lon: 3, precipitation: 3, time: 3, x: 2, y: 2)
Coordinates:
  * precipitation   (precipitation) <U4 'x' 'y' 'time'
  * lon             (lon) object 'x' 'y' [[-99.83, -99.32], [-99.79, -99.23]]
  * lat             (lat) object 'x' 'y' [[42.25, 42.21], [42.63, 42.59]]
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 21.53 3.692 15.57 ... 13.56 14.92 11.66

In [24]:
xr.Dataset(dict(bar=foo))

<xarray.Dataset>
Dimensions:  (space: 3, time: 4)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'
Data variables:
    bar      (time, space) float64 0.4995 0.6593 0.9157 ... 0.2261 0.6548 0.9839

In [25]:
xr.Dataset(dict(bar=foo.to_pandas()))

<xarray.Dataset>
Dimensions:  (space: 3, time: 4)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) object 'IA' 'IL' 'IN'
Data variables:
    bar      (time, space) float64 0.4995 0.6593 0.9157 ... 0.2261 0.6548 0.9839

### Dataset contents