In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr

### Positional indexing

In [2]:
da = xr.DataArray(np.random.rand(4, 3),
                  [('time', pd.date_range('2000-01-01', periods=4)),
                   ('space', ['WA', 'OR', 'CA'])])
da[:2]

<xarray.DataArray (time: 2, space: 3)>
array([[0.81419348, 0.28555516, 0.18315992],
       [0.89982837, 0.3386465 , 0.44363956]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02
  * space    (space) <U2 'WA' 'OR' 'CA'

In [3]:
da[0, 0]

<xarray.DataArray ()>
array(0.81419348)
Coordinates:
    time     datetime64[ns] 2000-01-01
    space    <U2 'WA'

In [4]:
da[:, [2, 1]]

<xarray.DataArray (time: 4, space: 2)>
array([[0.18315992, 0.28555516],
       [0.44363956, 0.3386465 ],
       [0.64243664, 0.31211562],
       [0.03883976, 0.84375516]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'CA' 'OR'

In [5]:
da.loc['2000-01-01':'2000-01-02', 'OR']

<xarray.DataArray (time: 2)>
array([0.28555516, 0.3386465 ])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02
    space    <U2 'OR'

In [6]:
da.loc['2000-01-01':'2000-01-02', ['WA', 'CA']] = 0
da

<xarray.DataArray (time: 4, space: 3)>
array([[0.        , 0.28555516, 0.        ],
       [0.        , 0.3386465 , 0.        ],
       [0.49319102, 0.31211562, 0.64243664],
       [0.49702436, 0.84375516, 0.03883976]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'WA' 'OR' 'CA'

### Indexing with dim names

In [7]:
da[dict(space=0, time=slice(None, 2))]

<xarray.DataArray (time: 2)>
array([0., 0.])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02
    space    <U2 'WA'

In [8]:
da.loc[{'time': slice('2000-01-01', '2000-01-01')}]

<xarray.DataArray (time: 1, space: 3)>
array([[0.        , 0.28555516, 0.        ]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01
  * space    (space) <U2 'WA' 'OR' 'CA'

In [9]:
da.isel(space=0, time=slice(None, 2))

<xarray.DataArray (time: 2)>
array([0., 0.])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02
    space    <U2 'WA'

In [10]:
da.sel(time=slice('2000-01-01', '2000-01-01'))

<xarray.DataArray (time: 1, space: 3)>
array([[0.        , 0.28555516, 0.        ]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01
  * space    (space) <U2 'WA' 'OR' 'CA'

### Nearest neighbor lookups