In [1]:
import numpy as np
import pandas as pd
import xarray as xr

In [5]:
data = xr.DataArray(
    np.random.randn(2, 3), dims=('x', 'y'), coords={'x': [10, 20]})
data

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.78270037, -0.28126364,  0.05460126],
       [-0.17433222, -0.39345463, -0.14115601]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y

In [4]:
xr.DataArray(pd.Series(range(3), index=list('abc'), name='foo'))

<xarray.DataArray 'foo' (dim_0: 3)>
array([0, 1, 2])
Coordinates:
  * dim_0    (dim_0) object 'a' 'b' 'c'

In [6]:
data.values

array([[ 0.78270037, -0.28126364,  0.05460126],
       [-0.17433222, -0.39345463, -0.14115601]])

In [7]:
type(data.values)

numpy.ndarray

In [8]:
data.dims

('x', 'y')

In [9]:
data.coords

Coordinates:
  * x        (x) int64 10 20

In [10]:
data.attrs

{}

In [11]:
data[0, :]

<xarray.DataArray (y: 3)>
array([ 0.78270037, -0.28126364,  0.05460126])
Coordinates:
    x        int64 10
Dimensions without coordinates: y

In [12]:
data.loc[10]

<xarray.DataArray (y: 3)>
array([ 0.78270037, -0.28126364,  0.05460126])
Coordinates:
    x        int64 10
Dimensions without coordinates: y

In [13]:
data.isel(x=0)

<xarray.DataArray (y: 3)>
array([ 0.78270037, -0.28126364,  0.05460126])
Coordinates:
    x        int64 10
Dimensions without coordinates: y

In [14]:
data.sel(x=10)

<xarray.DataArray (y: 3)>
array([ 0.78270037, -0.28126364,  0.05460126])
Coordinates:
    x        int64 10
Dimensions without coordinates: y

In [15]:
data.attrs['long_name'] = 'random velocity'
data.attrs['units'] = 'm/s'
data.attrs['description'] = 'A random variable created as an example'
data.attrs['random_attribute'] = 123
data.attrs

{'long_name': 'random velocity',
 'units': 'm/s',
 'description': 'A random variable created as an example',
 'random_attribute': 123}

In [16]:
data + 10

<xarray.DataArray (x: 2, y: 3)>
array([[10.78270037,  9.71873636, 10.05460126],
       [ 9.82566778,  9.60654537,  9.85884399]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y

In [18]:
np.sin(data)

<xarray.DataArray (x: 2, y: 3)>
array([[ 0.70519659, -0.27756986,  0.05457414],
       [-0.17345052, -0.38338136, -0.14068772]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y
Attributes:
    long_name:         random velocity
    units:             m/s
    description:       A random variable created as an example
    random_attribute:  123

In [19]:
data.T

<xarray.DataArray (y: 3, x: 2)>
array([[ 0.78270037, -0.17433222],
       [-0.28126364, -0.39345463],
       [ 0.05460126, -0.14115601]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y
Attributes:
    long_name:         random velocity
    units:             m/s
    description:       A random variable created as an example
    random_attribute:  123

In [20]:
data.sum()

<xarray.DataArray ()>
array(-0.15290487)

In [21]:
data.sum(axis=1)

<xarray.DataArray (x: 2)>
array([ 0.556038  , -0.70894286])
Coordinates:
  * x        (x) int64 10 20

In [22]:
data.mean(dim='x')

<xarray.DataArray (y: 3)>
array([ 0.30418408, -0.33735914, -0.04327737])
Dimensions without coordinates: y

In [23]:
a = xr.DataArray(np.random.randn(3), [data.coords['y']])
b = xr.DataArray(np.random.randn(4), dims='z')
a

<xarray.DataArray (y: 3)>
array([-0.23913307,  0.01381524,  1.05227142])
Coordinates:
  * y        (y) int64 0 1 2

In [24]:
b

<xarray.DataArray (z: 4)>
array([-0.04472048, -0.97091024,  0.56003134, -0.78669895])
Dimensions without coordinates: z

In [25]:
a + b

<xarray.DataArray (y: 3, z: 4)>
array([[-0.28385355, -1.21004332,  0.32089827, -1.02583202],
       [-0.03090524, -0.957095  ,  0.57384658, -0.77288371],
       [ 1.00755094,  0.08136118,  1.61230276,  0.26557247]])
Coordinates:
  * y        (y) int64 0 1 2
Dimensions without coordinates: z

In [26]:
data - data.T

<xarray.DataArray (x: 2, y: 3)>
array([[0., 0., 0.],
       [0., 0., 0.]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y

In [27]:
data[:-1] - data[:1]

<xarray.DataArray (x: 1, y: 3)>
array([[0., 0., 0.]])
Coordinates:
  * x        (x) int64 10
Dimensions without coordinates: y