In [2]:
import networkx as nx
import numpy as np
import pandas as pd
from nxpd import draw, nxpdParams

nxpdParams['show'] = 'ipynb'

In [3]:
n = 100
lmbda = 25

In [8]:
n_connections_each = np.random.poisson(lmbda, size=n)
n_connections_each[:10]

array([24, 27, 25, 33, 21, 29, 17, 30, 17, 35])

In [6]:
connection_probs = n_connections / n_connections.sum()
connection_probs[:10]

array([0.00900196, 0.01369863, 0.01252446, 0.00861057, 0.0109589 ,
       0.01252446, 0.0109589 , 0.00821918, 0.00861057, 0.01291585])

In [7]:
adj_matrix = np.zeros([n, n])

In [9]:
def get_random_connections(idx, n_connections_each, n):
    n_connections = n_connections_each[idx]
    ps = n_connections_each.copy()
    ps[idx] = 0
    ps = ps / ps.sum()
    return np.random.choice(
        range(n), size=n_connections, replace=False, p=ps)

In [10]:
get_random_connections(0, n_connections_each, n)

array([87, 93, 50,  3, 30, 12, 11, 28, 31, 49, 83, 80, 81, 46,  5, 13, 86,
       91, 78, 96, 10, 55, 53, 52])