In [1]:
import numpy as np

In [2]:
v = np.array([2, 5, 4, 7])
u = np.array([4, 1, 0, 2])
np.dot(u, v)

27

In [3]:
a, b, c = 1, 2, -3
u = np.array([4, 5, 1])
v = np.array([-4, 0, -4])
w = np.array([1, 3, 2])
a*u + b*v + c*w

array([ -7,  -4, -13])

In [5]:
np.outer(u, w)

array([[ 4, 12,  8],
       [ 5, 15, 10],
       [ 1,  3,  2]])

In [6]:
# Hadamard (pairwise)
u * v

array([-16,   0,  -4])

In [7]:
v = np.array([2, 5, 4, 7])
v_norm = np.linalg.norm(v)
v_norm

9.695359714832659

In [8]:
unit = v / v_norm
unit

array([0.20628425, 0.51571062, 0.4125685 , 0.72199487])

In [11]:
v = [7, 4 -5, 8, 3]
o = np.ones(len(v))
avg = np.dot(v, o) / len(v)
avg

4.25

In [12]:
sum(v) / len(v)

4.25

In [13]:
w = np.random.rand(len(v)) # random weights
print('weights:', w)
weighted_avg = np.dot(v, w / sum(w))
weighted_avg

weights: [0.09768574 0.33745085 0.14844645 0.06958214]


2.668034693140668