In [1]:
import numpy as np
from   scipy.linalg import hankel, toeplitz

In [2]:
A = np.random.randn(2, 5)
A

array([[-1.28192804,  1.91690957, -1.31028111,  1.15971899, -0.87188423],
       [-2.36282849,  1.66680785,  0.35277349, -1.00244031,  0.00918626]])

In [4]:
A.T

array([[-1.28192804, -2.36282849],
       [ 1.91690957,  1.66680785],
       [-1.31028111,  0.35277349],
       [ 1.15971899, -1.00244031],
       [-0.87188423,  0.00918626]])

In [5]:
np.transpose(A)

array([[-1.28192804, -2.36282849],
       [ 1.91690957,  1.66680785],
       [-1.31028111,  0.35277349],
       [ 1.15971899, -1.00244031],
       [-0.87188423,  0.00918626]])

In [6]:
I4 = np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
O4 = np.ones(4)
O4

array([1., 1., 1., 1.])

In [8]:
Z4_4 = np.zeros((4, 4))
Z4_4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
D = np.diag([1, 2, 3, 4])
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [10]:
R = np.random.randn(3, 4)
R

array([[-0.25225186,  0.804754  ,  1.07987037,  1.61319304],
       [ 0.04414215, -0.26656587, -1.15798515, -1.46524048],
       [-0.54582317,  0.66990524, -0.50501557,  1.60161906]])

In [11]:
np.diag(R)

array([-0.25225186, -0.26656587, -0.50501557])

In [14]:
A = np.random.randn(3, 2)
B = np.random.randn(3, 4)
AB = np.concatenate((A, B), axis=1)
AB.round(2)

array([[-1.88,  1.13, -0.54,  0.58, -1.54, -0.08],
       [ 0.59, -0.75,  0.21, -1.55,  0.36, -0.24],
       [ 2.31,  0.09,  0.9 , -1.35,  0.48, -1.63]])

In [17]:
A = np.random.randn(5, 5)
L = np.tril(A)
L.round(2)

array([[-0.9 ,  0.  ,  0.  ,  0.  ,  0.  ],
       [ 1.9 , -0.04,  0.  ,  0.  ,  0.  ],
       [-1.36, -1.17,  0.78,  0.  ,  0.  ],
       [ 0.68, -0.18,  0.23,  0.71,  0.  ],
       [ 0.34,  0.98,  0.72, -1.32, -0.62]])

In [18]:
U = np.triu(A)
U.round(2)

array([[-0.9 , -2.25, -0.92, -0.45, -0.78],
       [ 0.  , -0.04,  0.56,  1.71,  0.93],
       [ 0.  ,  0.  ,  0.78,  1.18,  0.2 ],
       [ 0.  ,  0.  ,  0.  ,  0.71,  1.29],
       [ 0.  ,  0.  ,  0.  ,  0.  , -0.62]])

In [19]:
t = [1, 2, 3, 4]
T = toeplitz(t)
T

array([[1, 2, 3, 4],
       [2, 1, 2, 3],
       [3, 2, 1, 2],
       [4, 3, 2, 1]])

In [21]:
H = hankel(t, r=[2, 3, 4, 1])
H

array([[1, 2, 3, 4],
       [2, 3, 4, 3],
       [3, 4, 3, 4],
       [4, 3, 4, 1]])

In [22]:
lmb = 0.01
I = np.eye(4)
A = np.random.randn(4, 4)
A

array([[ 1.78501581, -0.21208681, -0.04209628,  0.74637958],
       [ 0.53894192,  0.23079716, -1.40159922, -0.85243471],
       [-0.0150299 , -0.64750916, -2.20134668,  0.77635108],
       [ 0.38649493, -1.37860228,  0.07308655,  1.88724148]])

In [23]:
A_shift = A + lmb*I
A_shift

array([[ 1.79501581, -0.21208681, -0.04209628,  0.74637958],
       [ 0.53894192,  0.24079716, -1.40159922, -0.85243471],
       [-0.0150299 , -0.64750916, -2.19134668,  0.77635108],
       [ 0.38649493, -1.37860228,  0.07308655,  1.89724148]])

In [25]:
A = np.random.randn(4, 4)
np.trace(A)

1.743058349393054

In [27]:
A = np.random.randn(4, 2)
B = np.random.randn(4, 2)
C = np.zeros((2, 2))

for i in range(2):
    for j in range(2):
        C[i, j] = np.dot(A[:, i], B[:, j])
        
C

array([[ 0.21164277,  0.63946204],
       [-1.31996931, -0.22327268]])

In [29]:
A = np.random.randn(4, 4)
Al = np.tril(A)
S = Al + Al.T
S.round(2)

array([[ 0.19, -0.29, -1.57, -0.42],
       [-0.29,  0.56,  0.49,  0.26],
       [-1.57,  0.49,  1.06,  0.35],
       [-0.42,  0.26,  0.35,  1.73]])

In [31]:
D = np.zeros((4, 8))
for i in range(min(D.shape)):
    D[i, i] = i + 1
    
D

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0.]])