In [1]:
import numpy as np

In [5]:
M = np.random.randn(3, 3)
N = np.random.randn(3, 3)
P = M @ N
P.round(2)

array([[ 0.4 ,  1.88, -0.7 ],
       [ 1.3 , -1.5 ,  2.61],
       [-0.55, -3.08,  1.59]])

In [6]:
(N @ M).round(2)

array([[ 0.48, -1.39,  1.2 ],
       [ 1.98,  0.72, -1.56],
       [ 0.01,  0.4 , -0.72]])

In [7]:
(M * N).round(2)  # element-wise

array([[ 0.43,  0.12, -0.31],
       [-0.24, -1.62,  0.01],
       [ 0.04, -0.52, -0.92]])

In [8]:
A = np.array(
    [[1, 2, 3],
     [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
A.flatten()

array([1, 2, 3, 4, 5, 6])

In [11]:
A.flatten(order='F')

array([1, 4, 2, 5, 3, 6])

In [12]:
# Frobenius dot prod
np.trace(M.T @ N)

-3.006886631626301

In [14]:
A = np.random.randn(2, 4)
B = np.random.randn(4, 3)
P = np.zeros((2, 3))

for i in range(4):
    P += np.outer(A[:, i], B[i, :])
    
P - A@B  # ~ 0

array([[ 0.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 1.11022302e-16,  0.00000000e+00,  2.22044605e-16]])

In [15]:
D = np.diag(np.arange(1, 5))
A = np.random.randn(4, 4)
C1 = D * A
C2 = D @ A
(np.diag(C1), np.diag(C2))

(array([ 0.33239072, -2.43117566,  3.49991306,  1.00940677]),
 array([ 0.33239072, -2.43117566,  3.49991306,  1.00940677]))

In [17]:
A = np.diag(np.random.rand(3))
A

array([[0.48338303, 0.        , 0.        ],
       [0.        , 0.73471096, 0.        ],
       [0.        , 0.        , 0.78441434]])

In [18]:
C1 = (A.T + A) / 2
C2 = A.T @ A

C1 - np.sqrt(C2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
n = 5
A = np.random.randn(n, n)
v = np.random.randn(n)

LHS = np.linalg.norm(A @ v)
RHS = np.linalg.norm(A, ord='fro') * np.linalg.norm(v)

RHS > LHS # should always be true

True