In [1]:
import numpy as np
from   scipy.linalg import null_space

In [2]:
A = np.random.randn(3, 4)
null_space(A)

array([[ 0.05983277],
       [-0.8166076 ],
       [-0.18550106],
       [ 0.54328761]])

In [3]:
# reduced rank mats
A = np.random.randn(4, 3) @ np.random.randn(3, 4)
B = np.random.randn(4, 3) @ np.random.randn(3, 4)
null_A = null_space(A)
null_A

array([[ 0.30549887],
       [ 0.40600897],
       [-0.68157234],
       [ 0.52657981]])

In [5]:
B @ A @ null_A # ~0

array([[ 0.00000000e+00],
       [ 0.00000000e+00],
       [-4.44089210e-16],
       [ 8.32667268e-17]])

In [6]:
A @ B @ null_A # not 0

array([[-0.15786386],
       [-3.09127979],
       [ 3.55768326],
       [ 2.42649881]])

In [7]:
A = np.random.randn(16, 9) @ np.random.randn(9, 11)
null_r = null_space(A)
null_l = null_space(A.T)
r = np.linalg.matrix_rank(A)
r

9

In [8]:
(null_r.shape[1] + r), (null_l.shape[1] + r)

(11, 16)