In [1]:
import numpy as np

In [3]:
z = complex(3, 4)
z

(3+4j)

In [4]:
Z = np.zeros(2, dtype=complex)
Z[0] = 3+4j
Z

array([3.+4.j, 0.+0.j])

In [5]:
r = np.random.randint(-3, 4, size=3)
im = np.random.randint(-3, 4, size=3)
Z = r + im*1j
Z

array([-2.-1.j, -1.-3.j,  2.-2.j])

In [6]:
Z.conj()

array([-2.+1.j, -1.+3.j,  2.+2.j])

In [7]:
v = [0, 1j]
np.dot(v, v)  # normal dot prod

(-1+0j)

In [8]:
np.vdot(v, v)  # hermitian dot prod (mult by conj)

(1+0j)

In [9]:
U = 0.5 * np.array([[1+1j, 1-1j], [1-1j, 1+1j]])
U

array([[0.5+0.5j, 0.5-0.5j],
       [0.5-0.5j, 0.5+0.5j]])

In [10]:
# Hermitian
U @ np.matrix(U).H

matrix([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]])

In [11]:
# Non-Hermitian
U @ U.T

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

In [13]:
r = np.random.randn(3, 3)
im = np.random.randn(3, 3)
A = np.matrix(r + im*1j)
A.round(2)

matrix([[ 0.22+0.14j, -0.27-0.99j, -1.9 +1.2j ],
        [ 0.66+0.69j,  1.65+0.7j , -0.24-0.06j],
        [ 0.76-0.01j, -0.42-0.94j, -0.61+1.17j]])

In [15]:
A1 = A + A.H
A1.round(2)

matrix([[ 0.44+0.j  ,  0.39-1.68j, -1.14+1.21j],
        [ 0.39+1.68j,  3.3 +0.j  , -0.66+0.88j],
        [-1.14-1.21j, -0.66-0.88j, -1.22+0.j  ]])

In [20]:
np.diag(A1)  # no imaginary part

array([ 0.44387571+0.j,  3.30373193+0.j, -1.22496098+0.j])

In [21]:
A2 = A @ A.H
A2.round(2)

matrix([[ 6.18+0.j  , -0.51-1.9j ,  3.77+1.74j],
        [-0.51+1.9j ,  4.2 +0.j  , -0.77+2.11j],
        [ 3.77-1.74j, -0.77-2.11j,  3.37+0.j  ]])

In [23]:
np.diag(A2)

array([6.17618189+0.j, 4.19871582+0.j, 3.36605537+0.j])

In [24]:
# Test for Hermitian
A1 - A1.H

matrix([[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]])

In [25]:
A2 - A2.H

matrix([[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]])