In [3]:
import numpy as np
from   scipy.linalg import lu
import sympy as sym

In [7]:
A = np.random.randn(4, 3)
# LU Decomp:
P, L, U = lu(A)

In [13]:
np.abs(P @ L @ U - A) < 0.0000001

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
A.round(2)

array([[ 1.47, -1.09, -0.19],
       [-0.14,  1.03,  0.1 ],
       [-1.75,  0.43,  0.37],
       [ 0.66,  0.95, -0.35]])

In [11]:
(P @ L @ U).round(2)

array([[ 1.47, -1.09, -0.19],
       [-0.14,  1.03,  0.1 ],
       [-1.75,  0.43,  0.37],
       [ 0.66,  0.95, -0.35]])

In [14]:
A = np.random.randn(2, 4)
sym.Matrix(A).rref()

(Matrix([
 [1, 0,  -0.1593380956352, -1.10715695126099],
 [0, 1, 0.134552866210513,    2.404574384768]]),
 (0, 1))

In [15]:
A = np.array([[2, 0, -3], [3, 1, 4], [1, 0, -1]])
x = [2, 3, 4]
b = A @ x
b

array([-8, 25, -2])

In [16]:
A = np.random.randn(3, 6)
sym.Matrix(A).rref()[0]

Matrix([
[1, 0, 0,  8.94575778762661, -3.01238579065797, -14.3725700623229],
[0, 1, 0,  18.0131440545265, -5.37585731415378,  -27.817983171727],
[0, 0, 1, -14.2860875246961,  6.85761480848546,  21.3787792854433]])