In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym

In [3]:
A = np.random.randn(3, 3)
Ai = np.linalg.inv(A)
(A @ Ai).round(3)

array([[ 1., -0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [4]:
A = np.random.randn(3, 3)
Acat = np.concatenate((A, np.eye(3, 3)), axis=1)
Acat.round(3)

array([[ 0.148, -0.407, -0.755,  1.   ,  0.   ,  0.   ],
       [ 0.374, -0.419, -0.653,  0.   ,  1.   ,  0.   ],
       [ 0.567,  0.285,  0.751,  0.   ,  0.   ,  1.   ]])

In [8]:
Ar = sym.Matrix(Acat).rref()[0]
Ar = Ar[:, 3:]  # inverse
Ai = np.linalg.inv(A)
Ar - Ai

Matrix([
[ -2.1316282072803e-14,  1.95399252334028e-14, -4.44089209850063e-15],
[-1.27897692436818e-13,   9.9475983006414e-14,  -3.5527136788005e-14],
[  6.3948846218409e-14, -5.32907051820075e-14,  1.59872115546023e-14]])

In [11]:
A = np.random.randn(5, 3)
Al = np.linalg.inv(A.T @ A) @ A.T
(Al @ A).round(4)

array([[ 1., -0., -0.],
       [-0.,  1.,  0.],
       [-0.,  0.,  1.]])

In [13]:
m = 4
A = np.random.randn(m, m)

M = np.zeros((m, m))
G = M.copy()

for i in range(m):
    for j in range(m):
        rows = [True] * m
        rows[i] = False
        cols = [True] * m
        cols[j] = False
        M[i, j] = np.linalg.det(A[rows, :][:, cols])
        G[i, j] = (-1) ** (i + j)
        
C = M * G
Ai = C.T / np.linalg.det(A)
AiI = np.linalg.inv(A)
(AiI - Ai).round(5)

array([[-0., -0.,  0.,  0.],
       [ 0.,  0., -0.,  0.],
       [ 0., -0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
A = np.random.randn(5, 5)
Ai = np.linalg.inv(A)
Api = np.linalg.pinv(A)
(Ai - Api).round(6)

array([[-0., -0.,  0.,  0.,  0.],
       [ 0.,  0., -0., -0.,  0.],
       [-0.,  0.,  0.,  0.,  0.],
       [-0., -0.,  0.,  0., -0.],
       [ 0.,  0., -0., -0.,  0.]])

In [16]:
T = np.random.randn(5, 3)
Tl = np.linalg.inv(T.T @ T) @ T.T  # left inv
Tpi = np.linalg.pinv(T)
(Tl - Tpi).round(7)

array([[-0., -0., -0., -0.,  0.],
       [-0., -0., -0., -0.,  0.],
       [-0., -0., -0., -0.,  0.]])