In [1]:
import numpy as np

In [3]:
A = [[1, 2], [3, 1], [1, 1]]
b = [5.5, -3.5, 1.5]
np.linalg.lstsq(A, b, rcond=None)[0]

array([-2.5,  4. ])

In [4]:
A = np.random.randn(4, 3)
Q, R = np.linalg.qr(A)

In [5]:
A.round(2)

array([[ 0.05,  1.69, -0.39],
       [-0.55,  1.4 ,  0.66],
       [ 0.78,  0.81,  0.84],
       [-0.07, -0.6 ,  2.07]])

In [6]:
(Q @ R).round(2)

array([[ 0.05,  1.69, -0.39],
       [-0.55,  1.4 ,  0.66],
       [ 0.78,  0.81,  0.84],
       [-0.07, -0.6 ,  2.07]])

In [7]:
Q.round(2)

array([[-0.05, -0.7 ,  0.13],
       [ 0.58, -0.58, -0.34],
       [-0.81, -0.34, -0.33],
       [ 0.07,  0.25, -0.87]])

In [11]:
m, n = 4, 4
A = np.random.randn(m, n)
Q = np.zeros((m, n))

for i in range(n):
    Q[:, i] = A[:, i]
    # orthogonalize
    a = A[:, i]
    for j in range(i):
        q = Q[:, j]
        Q[:, i] = Q[:, i] - np.dot(a, q) / np.dot(q, q) * q
    # normalize
    Q[:, i] = Q[:, i] / np.linalg.norm(Q[:, i])

In [12]:
Q2, R = np.linalg.qr(A)

In [13]:
(Q - Q2).round(5)

array([[ 0.,  0.,  0., -0.],
       [-0., -0.,  0.,  0.],
       [ 0., -0., -0.,  0.],
       [ 0.,  0.,  0.,  0.]])